# Generated by Django 4.0.5 on 2022-06-08 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='nome', max_length=100)),
                ('cpf', models.CharField(db_column='cpf', max_length=14, unique=True)),
                ('nascimento', models.DateField(blank=True, db_column='nascimento')),
                ('sexo', models.SmallIntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')], db_column='sexo')),
            ],
            options={
                'verbose_name': 'Participantes',
                'verbose_name_plural': 'Participantes',
                'db_table': 'participante',
            },
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='nome', max_length=100)),
                ('data', models.DateField()),
                ('descricao', models.TextField(blank=True)),
                ('participantes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participacoes.participante')),
            ],
            options={
                'verbose_name': 'Retiro',
                'verbose_name_plural': 'Retiros',
                'db_table': 'retiro',
            },
        ),
    ]
