# Generated by Django 4.0.5 on 2022-06-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='estadocivil',
            field=models.SmallIntegerField(choices=[(1, 'Casado Civil'), (2, 'Casado Religioso'), (3, 'Sacramento'), (4, 'Batismo'), (5, 'Eucaristia'), (6, 'Crisma')], db_column='estadocivil', default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='retiro',
            name='participantes',
        ),
        migrations.AddField(
            model_name='retiro',
            name='participantes',
            field=models.ManyToManyField(blank=True, to='participacoes.participante'),
        ),
    ]
